
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftSUMARESTAleftMULTIPLICACIONDIVISIONCARACTER COMA COMILLA_DER COMILLA_IZQ CONSTANTE DIVISION DosPuntos ERROR_IDENTIFICADOR ERROR_IDENTIFICADOR_NUM ERROR_LEXICO IDENTIFICADOR IGUAL MULTIPLICACION PALABRA_RESERVADA_ENTONCES PALABRA_RESERVADA_FALSO PALABRA_RESERVADA_FIN PALABRA_RESERVADA_HACER PALABRA_RESERVADA_IMPRIMIR_BOLEANO PALABRA_RESERVADA_IMPRIMIR_CADENA PALABRA_RESERVADA_IMPRIMIR_NUMERO PALABRA_RESERVADA_INICIO PALABRA_RESERVADA_LEER_BOLEANO PALABRA_RESERVADA_LEER_CADENA PALABRA_RESERVADA_LEER_NUMERO PALABRA_RESERVADA_MIENTRAS PALABRA_RESERVADA_SI PALABRA_RESERVADA_SINO PALABRA_RESERVADA_VERDADERO PAREN_DER PAREN_IZQ PROGRAMA PuntoYComa RESTA SUMA TEXTO TEXTO_MAL_FORMADO TIPO_DATOprograma : PROGRAMA DosPuntos bloque\n               | expresion PuntoYComa\n               | asignacionbloque : PALABRA_RESERVADA_INICIO instrucciones PALABRA_RESERVADA_FIN\n              | instruccionesinstrucciones : instruccion\n                    | instrucciones instruccioninstruccion : asignacion\n                  | expresion PuntoYComaasignacion : IDENTIFICADOR IGUAL expresion PuntoYComa\n                 | IDENTIFICADOR IGUAL expresionexpresion : expresion SUMA expresion\n                | expresion RESTA expresion\n                | expresion MULTIPLICACION expresion\n                | expresion DIVISION expresionexpresion : PAREN_IZQ expresion PAREN_DERexpresion : IDENTIFICADORexpresion : CONSTANTE'
    
_lr_action_items = {'PROGRAMA':([0,],[2,]),'PAREN_IZQ':([0,5,7,8,10,11,12,13,15,16,18,19,20,21,24,25,26,27,28,29,30,31,32,33,],[5,5,-18,5,5,5,5,5,-17,5,5,5,-6,-8,-12,-13,-14,-15,-16,-11,5,-7,-9,-10,]),'IDENTIFICADOR':([0,5,7,8,10,11,12,13,15,16,18,19,20,21,24,25,26,27,28,29,30,31,32,33,],[6,15,-18,23,15,15,15,15,-17,15,23,23,-6,-8,-12,-13,-14,-15,-16,-11,23,-7,-9,-10,]),'CONSTANTE':([0,5,7,8,10,11,12,13,15,16,18,19,20,21,24,25,26,27,28,29,30,31,32,33,],[7,7,-18,7,7,7,7,7,-17,7,7,7,-6,-8,-12,-13,-14,-15,-16,-11,7,-7,-9,-10,]),'$end':([1,4,7,9,15,17,19,20,21,24,25,26,27,28,29,31,32,33,34,],[0,-3,-18,-2,-17,-1,-5,-6,-8,-12,-13,-14,-15,-16,-11,-7,-9,-10,-4,]),'DosPuntos':([2,],[8,]),'PuntoYComa':([3,6,7,15,22,23,24,25,26,27,28,29,],[9,-17,-18,-17,32,-17,-12,-13,-14,-15,-16,33,]),'SUMA':([3,6,7,14,15,22,23,24,25,26,27,28,29,],[10,-17,-18,10,-17,10,-17,-12,-13,-14,-15,-16,10,]),'RESTA':([3,6,7,14,15,22,23,24,25,26,27,28,29,],[11,-17,-18,11,-17,11,-17,-12,-13,-14,-15,-16,11,]),'MULTIPLICACION':([3,6,7,14,15,22,23,24,25,26,27,28,29,],[12,-17,-18,12,-17,12,-17,12,12,-14,-15,-16,12,]),'DIVISION':([3,6,7,14,15,22,23,24,25,26,27,28,29,],[13,-17,-18,13,-17,13,-17,13,13,-14,-15,-16,13,]),'IGUAL':([6,23,],[16,16,]),'PAREN_DER':([7,14,15,24,25,26,27,28,],[-18,28,-17,-12,-13,-14,-15,-16,]),'PALABRA_RESERVADA_FIN':([7,15,20,21,24,25,26,27,28,29,30,31,32,33,],[-18,-17,-6,-8,-12,-13,-14,-15,-16,-11,34,-7,-9,-10,]),'PALABRA_RESERVADA_INICIO':([8,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'expresion':([0,5,8,10,11,12,13,16,18,19,30,],[3,14,22,24,25,26,27,29,22,22,22,]),'asignacion':([0,8,18,19,30,],[4,21,21,21,21,]),'bloque':([8,],[17,]),'instrucciones':([8,18,],[19,30,]),'instruccion':([8,18,19,30,],[20,20,31,31,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> PROGRAMA DosPuntos bloque','programa',3,'p_programa','Compilador.py',222),
  ('programa -> expresion PuntoYComa','programa',2,'p_programa','Compilador.py',223),
  ('programa -> asignacion','programa',1,'p_programa','Compilador.py',224),
  ('bloque -> PALABRA_RESERVADA_INICIO instrucciones PALABRA_RESERVADA_FIN','bloque',3,'p_bloque','Compilador.py',231),
  ('bloque -> instrucciones','bloque',1,'p_bloque','Compilador.py',232),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones','Compilador.py',239),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones','Compilador.py',240),
  ('instruccion -> asignacion','instruccion',1,'p_instruccion','Compilador.py',247),
  ('instruccion -> expresion PuntoYComa','instruccion',2,'p_instruccion','Compilador.py',248),
  ('asignacion -> IDENTIFICADOR IGUAL expresion PuntoYComa','asignacion',4,'p_asignacion','Compilador.py',252),
  ('asignacion -> IDENTIFICADOR IGUAL expresion','asignacion',3,'p_asignacion','Compilador.py',253),
  ('expresion -> expresion SUMA expresion','expresion',3,'p_expresion_binaria','Compilador.py',257),
  ('expresion -> expresion RESTA expresion','expresion',3,'p_expresion_binaria','Compilador.py',258),
  ('expresion -> expresion MULTIPLICACION expresion','expresion',3,'p_expresion_binaria','Compilador.py',259),
  ('expresion -> expresion DIVISION expresion','expresion',3,'p_expresion_binaria','Compilador.py',260),
  ('expresion -> PAREN_IZQ expresion PAREN_DER','expresion',3,'p_expresion_parentesis','Compilador.py',264),
  ('expresion -> IDENTIFICADOR','expresion',1,'p_expresion_identificador','Compilador.py',268),
  ('expresion -> CONSTANTE','expresion',1,'p_expresion_numero','Compilador.py',272),
]
